### ISSUE TITLE
Contrast returns `Nan` results for blank images

### ISSUE THREAD

**Issue by amirmk89** [visual-layer/fastdup#102]
Hi,

When trying to get image statistics, blank white images get a contrast value of 0.0, while for blank black images I get a `Nan` in the dataframe. 
I've attached two images for reproducing.

Thanks
![000000541](https://user-images.githubusercontent.com/13304674/224555294-d936f25f-c1bc-42fe-8a4f-132fc5e5be6b.jpg)
![000051874](https://user-images.githubusercontent.com/13304674/224555295-fb7d9ee2-8686-4512-9711-4334700d4c2c.jpg)

**Comment by dbickson** [comment]
Fixed in 0.904
