### ISSUE TITLE
[DOCS] - Dead link for mini coco dataset

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#106]
The link to download the mini-coco dataset in this [tutorial](https://visual-layer.readme.io/docs/objects-and-bounding-boxes) seems to be invalid. The dataset could not be downloaded.

![image](https://user-images.githubusercontent.com/6821286/224905161-f4a2649b-5784-4586-9ceb-40535e0feb19.png)

**Comment by amirmk89** [comment]
Thank you for pointing this out. Added a link for the original repo for users that experience issues with the `gdown` app.
