### ISSUE TITLE
[FEATURE REQUEST] - Differentiation in the report name for bright vs dark stats gallery

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#107]
Currently, the title for both bright and dark image galleries is the same. Would it be good to have different names for them so that the report can be used outside of the notebook?

![image](https://user-images.githubusercontent.com/6821286/224906022-dddbd043-baff-490e-b048-583730235986.png)

**Comment by dbickson** [comment]
Should be fixed in 0.904
