### ISSUE TITLE
[DOCS] - URL typo

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#108]
Currently the URL for Cleaning and preparing an image dataset is set to https://visual-layer.readme.io/docs/abc

Is the `abc` in the URL intentional?

![image](https://user-images.githubusercontent.com/6821286/224906387-d661fdc9-9719-41b4-b38c-667c3151ab1a.png)

**Comment by amirmk89** [comment]
Hi @dnth, thank you for pointing this out.
This seems like an internal reference of the service hosting our docs.
