### ISSUE TITLE
[DOCS] - Incomplete docs on the `fd.run` method.

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#112]
Link to docs - https://visual-layer.readme.io/docs/v1-api#fastdup.engine.Fastdup.run

![image](https://user-images.githubusercontent.com/6821286/224909020-49c3802e-b8ac-4618-ad2b-4de62d24e543.png)

**Comment by amirmk89** [comment]
Thanks for the heads up, fixed.
