### ISSUE TITLE
Template for GitHub issues

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#114]
Shall we have a template on GitHub issues for users to file bug reports, feature requests, and docs improvements?

Useful links 

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

- https://github.com/devspace/awesome-github-templates

**Comment by amirmk89** [comment]
Great idea, would be very useful in triaging and routing.
