### ISSUE TITLE
[BUG] - White text `image` in saved `duplicates.html` file

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#117]
Is there a purpose for the white text on the top left corner?

![image](https://user-images.githubusercontent.com/6821286/224970918-d24aa217-85c9-4cff-901a-51230799e029.png)

It seems to be coming from this line of code

https://github.com/visual-layer/fastdup/blob/fa336f03508230c53fc8594110ad3d83badaad5b/fastdup/html_writer.py#L483

The text only appears in the saved `duplicates.html` and not visible in Jupyter notebooks.

Here's my `duplicates.html` file for reference.
https://raw.githubusercontent.com/dnth/clean-up-digital-life-fastdup-blogpost/main/fastdup_report/galleries/duplicates.html

**Comment by dbickson** [comment]
Should be fixed in 0.905
