### ISSUE TITLE
[BUG] - Confusing `type: unknown_unknown` text appears on image when there're no labels provided

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#118]
Is the text intentional?

![image](https://user-images.githubusercontent.com/6821286/224973379-5f213ec8-2ec6-441d-a4d0-0e0769252d94.png)

It seems to be coming from this line
https://github.com/visual-layer/fastdup/blob/fa336f03508230c53fc8594110ad3d83badaad5b/fastdup/galleries.py#L183

Here's my notebook for reference

https://github.com/dnth/clean-up-digital-life-fastdup-blogpost/blob/main/fastdup_analyze.ipynb

**Comment by dbickson** [comment]
Should be fixed in 0.904
