### ISSUE TITLE
Error when using overwrite argument.

### ISSUE THREAD

**Issue by pranavchaturved** [visual-layer/fastdup#122]
Fastdup Version:
Version: 0.906

Python Version:
3.8.16

OS:
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380

Error:
AssertionError: there is already an active fastup run on the working dir, change work_dir or run with overwrite=True.

Occurs when running:
fd.run(nearest_neighbors_k=nearest_neighbors_k,
               cc_threshold=cc_threshold,
               overwrite=True
               )

As I understand, overwrite=True is already being used but still I get error which says to use overwrite=True.

**Comment by ovednagar** [comment]
Hi 
Ee excluded this option for current version, Next version will include a safer overwrite option.

**Comment by dbickson** [comment]
Should be fixed in 0.908
