### ISSUE TITLE
[Bug] Similarity galleries ordering is reversed

### ISSUE THREAD

**Issue by amirmk89** [visual-layer/fastdup#138]
Hi,

When displaying a similarity gallery, the sprite image on the right has the most similar example to the far right, and the least similar to the left. See in this screenshot, the right-most one is a duplicate.
I think the correct ordering is such that the left-most one is the most similar.

![Screen Shot 2023-03-28 at 11 14 09](https://user-images.githubusercontent.com/13304674/228172584-000a8b64-80f6-49b3-bb25-d63531a313d8.png)

Thanks.

**Comment by dbickson** [comment]
Fixed in 0.911
