### ISSUE TITLE
Component gallery visualization `sort_by='area'` parameter not working correctly

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#139]
I'm on version 0.909 and find no difference in visualization when I run with bounding boxes.

`fd.vis.component_gallery(sort_by='comp_size')`

and 

`fd.vis.component_gallery(sort_by='area')`

To reproduce, run the above command with the object detection example https://colab.research.google.com/github/visual-layer/fastdup/blob/main/examples/analyzing-object-detection-dataset.ipynb

**Comment by dbickson** [comment]
Should be fixed in 0.910.
For sorting by comp size please use sort_by='comp_size',
for sorting by average image area or any other stats please use metric='size', metric='blur' etc.
