### ISSUE TITLE
[BUG]: Distored aspect ratio in Similarity Report

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#140]
I'm on version 0.910 and by running `fd.vis.similarity_gallery()` I find that the Similar images have distorted aspect ratio.

![image](https://user-images.githubusercontent.com/6821286/228428575-f7b32818-6646-4e0f-8009-fe2adc7bfa90.png)

**Comment by dbickson** [comment]
Hi @dnth there is a flag called keep_aspect_ratio=True you can send to the gallery and it should fix it. Can you check if it works and if so need to clarify the documentation and maybe change this flag to be True on default.

**Comment by dnth** [comment]
thanks @dbickson `fd.vis.similarity_gallery(keep_aspect_ratio=True)` works!

**Comment by dbickson** [comment]
I changed the default to be keep_aspect_ratio=True, fixed in 0.911
