### ISSUE TITLE
[Bug / Feature request] Stats and outlier gallery sorting

### ISSUE THREAD

**Issue by amirmk89** [visual-layer/fastdup#145]
Sorting isn't functional for outliers (bug) and stats (feature request) galleries:

Outliers - `ascending` argument is unused, and not passed to inner function `create_outliers_gallery`.

Stats - no 'ascending' argument, determined internally, could be enhanced like this:
```
# adding ascending=None or ascending='auto' to arguments
# fastdup/fastdup_visualizer.py:277

auto_ascending = False
        name = metric
        if metric == 'dark':
            metric = 'mean'
            auto_ascending = True
        elif metric == 'bright':
            metric = 'mean'
            auto_ascending = False
        if metric == 'blur':
            auto_ascending = True
ascending =  auto_ascending if ascending is None else ascending
```

Would be great to have an option to override the default sorting for specific use cases (debugging, slicing a value).

Thanks!

**Comment by dbickson** [comment]
Now when external_df is given, sorting is not done by the gallery but performed by the user before the call to the gallery.
I have fixed the sorting for the outliers, the sort_by column does not make sense and is removed for outliers. Fixed in v. 0.915
