### ISSUE TITLE
[Feature Request] Add `matplotlib` as dependency

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#149]
Running `fd.vis.stats_gallery(metric='dark')` requires `matplotlib` to be installed.

Can we include `matplotlib` as one of the dependencies of fastdup?

![image](https://user-images.githubusercontent.com/6821286/232643523-07cc6afa-1514-427e-a2f9-e4946cef6ff8.png)

**Comment by dbickson** [comment]
Thanks @dnth for reporting it was some stale code, I have removed it will be fixed in 0.919. We try not to depend on matplotlib as it is a big dependency which needs multipe other deps and has multiple backends which often collide with other install packages.
