### ISSUE TITLE
outliers() is missing outlier filename column

### ISSUE THREAD

**Issue by dbickson** [visual-layer/fastdup#154]
When I tried to list the outliers, some error pops up ("AttributeError: 'DataFrame' object has no attribute 'img_filename_outlier'"). I attached the screenshot in the attachment.

I am using version 0.917. It is clear that there is no "img_filename_outlier" in the outlier_df dataframe... (outlier_df = fd.outliers()) So I think that might be a compatibility problem?

Only "outlier"    "nearest"    "distance"    "index"    "filename_nearest"    "error_code_nearest"    "is_valid_nearest" are found.

Thanks

Best,

Zilun

![Screenshot from 2023-04-20 00-11-31](https://user-images.githubusercontent.com/4495523/233164571-5444cfa9-3cd7-4ad8-97f0-a61b455cee21.png)

**Comment by dnth** [comment]
I can confirm having this issue on fastdup version '0.921'

**Comment by dnth** [comment]
As a temporary workaround install an older version of fastdup. Version '0.906' should work.

**Comment by dbickson** [comment]
The solution is to change img_filename_outlier to filename_outlier. 
@dnth can you please update the docs accordingly?

**Comment by dnth** [comment]
@dbickson with the current version `fd.outliers()` does not produce a DataFrame with the name `filename_outlier`.

Changing `img_filename_outlier` to `filename_outlier` would also result in the same error. 

![image](https://user-images.githubusercontent.com/6821286/233952347-28c7e39c-7eba-4162-9f7d-19546708db41.png)

**Comment by dnth** [comment]
In version 0.906, `fd.outliers()` produces a DataFrame with the img_filename_outlier column 

![image](https://user-images.githubusercontent.com/6821286/233955665-7c5bc435-437c-4ebb-a813-86d444c5614e.png)

**Comment by dbickson** [comment]
Thanks @dnth for clarifying! We will fix this

**Comment by dbickson** [comment]
Fixed in 0.922
