### ISSUE TITLE
Searching for duplicates in large dataset

### ISSUE THREAD

**Issue by gilamsalem** [visual-layer/fastdup#155]
Hi,
Assuming I have a large dataset ~200m images. And assuming I would like to find duplicates every time a new image is arrived to my system. Is itnpossible tonuse fastdup for that? What will be the recommended setup for that?
Thanks!

**Comment by dbickson** [comment]
Hi @gilamsalem look at the `fastdup.init_search` and `fastdup.search()` methods https://visual-layer.readme.io/docs/v02xx-api#search. The current free version is limited to 1M image models. We would love to connect and explore collaboration, we are looking for companies who like to work with us as design partners and we could enable more advanced functionality. Internally we are working on an enterprise version which supports up to a billion image search. We will be happy to connect for a demo to share capabilities and performance.

**Comment by dbickson** [comment]
Example code is here: 


```
    Example:
        >>> import fastdup
        # point to the work_dir where fastdup was run
        >>> fastdup.init_search(10, 'search_out')
        >>> import cv2
        >>> from PIL import Image

        >>> img = Image.open('test_1234.jpg')
        >>> img = img.resize((224, 224), Image.Resampling.NEAREST)
        >>> img_size = 224 * 224
        >>> ret = fastdup.search(img, img_size, verbose=1)
```
