### ISSUE TITLE
surveillance camera doesn't include 'pip install fastdup'

### ISSUE THREAD

**Issue by roi2405** [visual-layer/fastdup#157]
![Screenshot 2023-04-22 212910](https://user-images.githubusercontent.com/73583326/233800751-3653ec78-9e55-4cef-afdb-89010e9f8e67.png)

**Comment by dnth** [comment]
Thank you for reporting this issue @roi2405! Were there any other issues you encountered? We'd like to make the notebook a better experience for you and others.
