### ISSUE TITLE
[Bug]: fastdup.search raises an Error: PIL.Image has not attribute 'Resampling'

### ISSUE THREAD

**Issue by roi2405** [visual-layer/fastdup#176]
### What happened?

after using 'fastdup.create' and 'fastdup.run', running 'fastdup.search' on the work directory that was used for 'fastdup.run' raises an attribute error as specified above.
note that it fails on the 'fastdup.search', and not on the 'fastdup.init_search'.

### What version of fastdup were you runnning on?

0.923

### What version of Python were you running on?

Python 3.10

### Operating System

Google Colab

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastdup/__init__.py", line 2082, in search
    img = img.resize((224, 224), Image.Resampling.NEAREST)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

### Attach a screenshot [Optional]

![image](https://user-images.githubusercontent.com/73583326/235270222-6b895577-507e-4353-a328-1575e958c735.png)

### Contact Details [Optional]

roi2405@gmail.com

**Comment by dbickson** [comment]
Fixed in 0.925
