### ISSUE TITLE
[Bug]: examples/image-search.ipynb not found

### ISSUE THREAD

**Issue by amiralush** [visual-layer/fastdup#182]
### What happened?

I'm getting an error message while trying to view the image search example notebook. 

### What did you expect to see?

The image search notebook :)

### What version of fastdup were you runnning on?

0.925

### What version of Python were you running on?

Python 3.10

### Operating System

macOS Ventura 13.0

### Reproduction steps

1. Click on the image search notebook under the "advanced features" section 

### Attach a screenshot [Optional]

<img width="999" alt="Screenshot 2023-05-02 at 20 39 17" src="https://user-images.githubusercontent.com/6663558/235742657-0f56e36b-80a1-4b88-8773-3585ec70e81c.png">
<img width="1307" alt="Screenshot 2023-05-02 at 20 35 26" src="https://user-images.githubusercontent.com/6663558/235742670-44247fbb-7ad7-42c3-8c5a-e04876f6ddc3.png">

**Comment by dnth** [comment]
Work on Colab but not on nbviewer. I find this weird too

**Comment by dnth** [comment]
It's working now @amiralush

**Comment by dbickson** [comment]
Working now
