### ISSUE TITLE
[Bug]: getting an error after import fastdup on Amazon Linux

### ISSUE THREAD

**Issue by amiralush** [visual-layer/fastdup#198]
### What happened?

<img width="663" alt="Screenshot 2023-05-16 at 23 14 52" src="https://github.com/visual-layer/fastdup/assets/6663558/fe805a5e-5f0f-406b-98c9-a83e27392d4f">

### What did you expect to see?

Clean import with no error

### What version of fastdup were you runnning on?

1.0

### What version of Python were you running on?

Python 3.9

### Operating System

Amazon Linux

### Reproduction steps

pip install fastdup
python >> import fastdup

### Relevant log output

```shell
PRETTY_NAME="Amazon Linux 2023"
Python 3.9.16 (main, Feb 23 2023, 00:00:00) 
[GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastdup
sh: line 1: dpkg: command not found
```

**Comment by dbickson** [comment]
Fixed in 1.2
