### ISSUE TITLE
[Feature Request]:  COCO formate read json

### ISSUE THREAD

**Issue by Lifeguard-alex** [visual-layer/fastdup#203]
### Feature Name

coco formate

### Feature Description

i dont see option to read coco formats json file for object detector

### Contact Information [Optional]

alex@lifeguard-ai.com

**Comment by amirmk89** [comment]
Hi Alex,
Thank you for reaching out.

We will add an example for loading COCO format annotation to the docs.
In the meanwhile, you can use the example shared [in this issue](https://github.com/visual-layer/fastdup/issues/84).

Amir
