### ISSUE TITLE
[Feature Request]: Simplify fastdup.create

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#213]
### Feature Name

Simplify fd.create

### Feature Description

Would it be more intuitive to have only the `input_dir` as the required argument? Users can optionally pass in the `work_dir` if they prefer.

This would simplify the `.create` line from

```python
fd = fastdup.create(work_dir="fastdup_work_dir/", input_dir="images/")
```
to

```python
fd = fastdup.create(input_dir="images/")
```

Since there's only one input (the path to images) there's little room for mistakes and confusion between the `input_dir` and `work_dir`

I think this might improve user experience 😃

**Comment by dbickson** [comment]
Fixed in 1.11
