### ISSUE TITLE
[Bug]: Invalid number of channels in input images where scn is 4

### ISSUE THREAD

**Issue by pgarciacamou** [visual-layer/fastdup#219]
## Similar Issue: https://github.com/visual-layer/fastdup/issues/190

----

### What happened?

When running fastdup via https://registry.hub.docker.com/r/karpadoni/fastdup-ubuntu-20.04/ I get the following error:

```bash
2023-06-25 23:43:19 [ERROR] Failed to read image /home/Photos/IMG_8034.PNG OpenCV(4.6.0) /mnt/data/openc
v/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl:
:{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, i
nt) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv:
:impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>:
:NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'          
> Invalid number of channels in input image:                                                         
>     'VScn::contains(scn)'                                                                          
> where                                                                                              
>     'scn' is 4
```

IMG_8034.PNG:
<img width="40%" src="https://github.com/visual-layer/fastdup/assets/8354571/41c2725b-836a-47a3-a872-e36140616a83">

### What version of fastdup were you runnning on?

1.17

### What version of Python were you running on?

Python 3.8

### Operating System

Ubuntu 20.04.6 LTS

### Reproduction steps

1. Run the docker container inside my DS220+ Synology NAS.
2. Run `python3 run_fastdup.py `

`run_fastdup.py`:

```py
import fastdup

# Set the working directory and the directory containing the images
work_dir = '/fastdup'
images_dir = '/home'

# Create a FastDup instance and run it
fd = fastdup.create(work_dir, images_dir)
fd.run()
```

**Comment by dbickson** [comment]
Hi @pgarciacamou. Thanks for the detailed error report! I looked at your image and it is somehow non standard. It is RGBA 16 bit. We have added a fix in version 1.21, it will be out today.

**Comment by dbickson** [comment]
Version 1.21 is out please try it out.

**Comment by pgarciacamou** [comment]
Tested it and it works as expected now. 👍 thank you!
