### ISSUE TITLE
[Bug]: Connected Components DataFrame does not match number of instances

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#237]
### What happened?

![image](https://github.com/visual-layer/fastdup/assets/6821286/7bd76015-1935-444d-bba5-4d6a4bda4afd)

### What did you expect to see?

They should match.

### What version of fastdup were you runnning on?

1.27

### What version of Python were you running on?

Python 3.10

### Operating System

Google Colab

### Reproduction steps

Run Colab notebook - https://colab.research.google.com/drive/10p5VGaVo-Lolwu3EG0c1vokhyYF_RouN#scrollTo=7MF3cowvjVF1

**Comment by dbickson** [comment]
HI @dnth, connected_components() now returns a dataframe with images that has other similar in their cluster. For images that are not present in any cluster there are no rows. Is there a specific reason you need a full dataframe? If so you can simply do comp = pd.read_csv(os.path.join(work_dir, 'connected_components.csv'))
