### ISSUE TITLE
[Feature Request]: Add Detection label and score in reports

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#238]
### Feature Name

Detection Label and Confidence

### Feature Description

For yolov5 detections, having labels and detection scores would provide more value to evaluate the quality of the detections.

For example, if there are outliers detected, then naturally we'd like to know the predicted class and confidence of the prediction. Knowing this information helps users debug the model and also datasets.

![image](https://github.com/visual-layer/fastdup/assets/6821286/cb8ac3fb-a463-4cd0-a286-d9ca024269e9)

**Comment by dbickson** [comment]
![Screen Shot 2023-07-24 at 13 03 44](https://github.com/visual-layer/fastdup/assets/4495523/e0296ca2-17ac-4b80-bae6-1ca62b754be4)

should be fixed now
