### ISSUE TITLE
[Bug]: Objects stated as images in output of run function

### ISSUE THREAD

**Issue by guy-singer** [visual-layer/fastdup#240]
### What happened?

In the output of the run function with annotations, under the dataset analysis section, objects detected in the dataset are mistakenly called "images" instead.

### What version of fastdup were you runnning on?

current version

### What version of Python were you running on?

Python 3.10

### Operating System

Ubuntu

### Reproduction steps

please see the example tutorial notebook "Analyzing Object Detection Dataset", which contains the error

### Attach a screenshot [Optional]

![Screen Shot 2023-07-30 at 15 13 48](https://github.com/visual-layer/fastdup/assets/23167588/b899caa1-6198-44a0-9773-7bcd3bfaedd3)

**Comment by dbickson** [comment]
Fixed in 1.31
