### ISSUE TITLE
[Feature Request]: num_images ordering

### ISSUE THREAD

**Issue by guy-singer** [visual-layer/fastdup#242]
### Feature Name

Num_images ordering

### Feature Description

Num_images likely returns the firs N images in the dataset, but nowhere in the documentation is this detailed. Two possible directions to improve:

1. Simple: specify that num_images returns the first N examples

2. Less simple: allow for selection patterns such as random sampling

**Comment by dbickson** [comment]
`input_dir` supports a python list of filenames, thus you can do the sampling in whatever policy you like and then send the list as an argument to fastdup that will work on those files.
