### ISSUE TITLE
[Bug]: Cropped files are not saving within the specified folder

### ISSUE THREAD

**Issue by VimukthiRandika1997** [visual-layer/fastdup#245]
### What happened?

```
fd.vis.component_gallery(metric='size', max_width=900, show=True,
                        # draw_bbox=True,
                        save_path=save_to('similarity_clusters'),
                        saving_artifact=True,
                        load_crop=True
                        )
```

### What did you expect to see?

Cropped images should be saved within the defined saving path. I even tried with the default option. But it did not seem to work either.

### What version of fastdup were you runnning on?

1.27

### What version of Python were you running on?

Python 3.9

### Operating System

Ubuntu 22.04

### Attach a screenshot [Optional]

![Screenshot from 2023-08-01 18-44-28](https://github.com/visual-layer/fastdup/assets/77375611/bfb0550b-6eb0-4758-b355-d7cb16c89a34)

**Comment by VimukthiRandika1997** [comment]
I found the error, if we want to save resulted crop files, then we need to set the command save_artifacts=True within the particular function, but the message displayed in the output log is misleading. For other functions, it is showing created crop files, but those would not be saved unless we use `save_artifacts` attribute. But in this case, crop files are not even showing.

**Comment by dbickson** [comment]
Hi @VimukthiRandika1997 apologies for the unclear documentation. Did you try to run() with the flag save_crops=1 ? this will make sure to save the bounding box crops into the crops subfolder.
