### ISSUE TITLE
[Bug]: Noisy printout

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#248]
### What happened?

When running fastdup with bounding box annotations, I see noise printout about additive margin. Refer screenshot below.

![image](https://github.com/visual-layer/fastdup/assets/6821286/8775abd0-c751-436f-aa53-0094acbb9fd0)

### What did you expect to see?

Clean printout with only necessary information.

### What version of fastdup were you runnning on?

1.33

### What version of Python were you running on?

Python 3.10

### Operating System

Ubuntu 22.04

### Reproduction steps

Run - https://colab.research.google.com/github/visual-layer/fastdup/blob/main/examples/analyzing-object-detection-dataset.ipynb

**Comment by dbickson** [comment]
Fixed in 1.34
