### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by RYWei** [visual-layer/fastdup#250]
### Feature Name

cluster_from_similarity_matrix

### Feature Description

Can fastDup cluster through calculated similarity information? I can't find the corresponding capability in the API documentation.

### Contact Information [Optional]

674850716@qq.com

**Comment by dbickson** [comment]
Yes.
Please look at `https://visual-layer.readme.io/docs/v1-api#fastdup.fastdup_controller.FastdupController.connected_components_grouped` and let us know if you have questions. This call runs after fastdup was run using fd.run(..).
