### ISSUE TITLE
[Feature Request]: Similarity.csv is not showing image names anymore, it shows index names.

### ISSUE THREAD

**Issue by abulus** [visual-layer/fastdup#255]
### Feature Name

image names

### Feature Description

Hi dear devs,

Currently I am using version 1.36 

In older versions we would be able to see image names at least on similarity.csv but not anymore. It shows indexes. 

If there is a hidden parameter that I can't see, please inform me. 

Thank you for your works.
![image_2023-08-21_133236801](https://github.com/visual-layer/fastdup/assets/79931475/c17549f6-1f4d-4190-9fb0-fe91c0f54bde)

**Comment by abulus** [comment]
Actually, If we directly run like `fastdup.run(input_dir="", work_dir=""` like this it shows image file paths in similarity.csv.

But if we follow the instructions from documentation: We go as follow: `fd = fastdup.create(work_dir, image_dir)
fd.run()` it shows index instead of image names.

**Comment by dbickson** [comment]
hi @abulus. In fastdup v1 you can do `fd.similarity()` to get the similar filenames. Please try it out and let us know if this works for you. 

```
import fastdup
fd = fastdup.create(input_dir=xxxx, work_dir=xxxx)
fd.run()
df = fd.similarity()
```

Thanks
