### ISSUE TITLE
[Bug]: Confusing Warning & Info Message

### ISSUE THREAD

**Issue by ohade** [visual-layer/fastdup#257]
### 1. Warning on none existing tar/zip files. Believe this is caused by the video files
<img width="1310" alt="pic1" src="https://github.com/visual-layer/fastdup/assets/13435149/b88656e9-18a6-4d47-bdfd-d9c409bbbd91">
<img width="617" alt="pic2" src="https://github.com/visual-layer/fastdup/assets/13435149/d40e71f3-3ff8-466a-8ac2-4b621367fbfd">
<img width="337" alt="pic3" src="https://github.com/visual-layer/fastdup/assets/13435149/0ad6300e-3041-47a1-9ca8-d0f2bf4b22ee">

--------------------------------------------------------------------------------<br>   

### 2. Calculation in the Summary report1:
<img width="906" alt="image" src="https://github.com/visual-layer/fastdup/assets/13435149/8ec05c6b-b657-4674-a07f-7c05f9f77101">
<br>   

### Explain:<br>   
**a.1.** If 100% is 11,678 pictures. how can 88% be 11,678.
**a.2.** If 88% are valid, why the rest 12% aren't invalid (showing 0%).   
**b.** 3,799 out of 11,678 are 32.5% not 28.63%. 
**c.** 7,879 out of 11,678 are 67.47% not 59.37%. 
**d.** 831 out of 11,678 are 7.11% not 6.26%.

--------------------------------------------------------------------------------<br>   

### 3. Calculation in the Summary report2:
<img width="817" alt="image" src="https://github.com/visual-layer/fastdup/assets/13435149/0e900da9-25f9-45a8-b1d4-a9a07ba3201e">

* 3152 are 26% not 13%
* 11,631 are 99.6 not 49.8% <--- is it really the case? 99.6% above 0.9?
* You mention that the outlier are with distance lower than 0.05, but on the following line you mention that the minimum distance found is 0.462, is that because you excluded the outliers from the min/max? 

### What did you expect to see?

Wrote inline

### What version of fastdup were you runnning on?

1.36

### What version of Python were you running on?

Python 3.10

### Operating System

MacOS Venture 13.2.1

### Reproduction steps

Wrote inline above

### Relevant log output

```shell
added above
```

### Attach a screenshot [Optional]

added above

### Contact Details [Optional]

ohadedelstain@gmail.com

**Comment by dbickson** [comment]
Hi @ohade thanks for reporting, indeed confusing printouts.
About the tar/zip file warning, we treat mp4 and avi as compressed files as we do frame extraction from them and save the extracted frames locally. Now imagine there are frames in the folders while having also frames inside the video with the same or similar names, the analysis of both raw video and extracted video frames my be mixed.  it may result in unclear behavior so we work on either the split frames or the video but not on a mix of both. The warning is totally unclear we will try to improve it. 

The counting printout is buggy we will fix. Some non images are getting into the count and messing it up. Maybe the videos. We will check.

**Comment by ohade** [comment]
Got it, thanks

**Comment by dbickson** [comment]
Now fixed in 1.38
