### ISSUE TITLE
[Bug]: Statistical gallery is out of order for bounding boxes analysis

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#265]
### What happened?

I ran `fd.vis.stats_gallery(metric='bright')` and found that the images are not sorted correctly. E.g. from brightest to darkest in the gallery.

![image](https://github.com/visual-layer/fastdup/assets/6821286/0e904f7f-f663-42c2-a6be-4ebbed1c8291)

### What did you expect to see?

Images are sorted correctly based on the specified metrics.

### What version of fastdup were you runnning on?

1.38

### What version of Python were you running on?

Python 3.10

### Operating System

Ubuntu 22.04

### Reproduction steps

Run Roboflow [notebook](https://colab.research.google.com/github/visual-layer/fastdup/blob/main/examples/analyzing-roboflow-datasets.ipynb).

**Comment by dbickson** [comment]
should be fixed on 1.40 on mac and 1.39 on ubuntu
