### ISSUE TITLE
[Bug]: coco to csv converter.

### ISSUE THREAD

**Issue by trathpai** [visual-layer/fastdup#268]
### What happened?

I cannot see any coco to csv converter

### What version of fastdup were you runnning on?

0.918

### What version of Python were you running on?

Python 3.10, Python 3.9

### Operating System

Ubuntu 22

**Comment by dnth** [comment]
Hi @trathpai, can I understand better what were you trying to accomplish? Was there any specific example you were working on? 

fastdup supports both .csv and COCO .json annotation format. 

+ See how to load the `.csv` annotation format in this [example](https://visual-layer.readme.io/docs/objects-and-bounding-boxes).

+ See how to load the `.json` file in this [example](https://visual-layer.readme.io/docs/roboflow-universe).

**Comment by trathpai** [comment]
I was looking for example to load json directly but could find the csv example only, which mentioned json to csv converter. If JSON is already supported then i can close this issue.

Maybe in official tutorial you can add this example as well.

Thanks for the input.
