### ISSUE TITLE
[Bug]: `PIL.Image` is 700+% faster than `fastdup_imread`

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#286]
### What happened?

fastdup uses a utility function `fastdup_imread` throughout the codebase. But I found that this function is very slow compared to using plain `PIL.Image`

My goal is to get a PIL Image from an image path.

+ Using `fastdup_imread`
![image](https://github.com/visual-layer/fastdup/assets/6821286/a7cedf17-8f96-458b-b0ff-d587f16f9bcb)

+ Using PIL
![image](https://github.com/visual-layer/fastdup/assets/6821286/26c123ab-b572-4e0a-8384-3033be899065)

That's a whopping 755.75% increase in run time when using `fastdup_imread`!

The difference is still large even when the codes to convert from BGR to RGB are commented out (243.08% increase). 
![image](https://github.com/visual-layer/fastdup/assets/6821286/c47f7f9b-4dca-4ab5-98b3-2eafa3536fc1)

I believe in a large dataset this difference will be significant.

### What did you expect to see?

A smaller difference in run time for both.

### What version of fastdup were you runnning on?

1.43

### What version of Python were you running on?

Python 3.10

### Operating System

Ubuntu 22.04

### Reproduction steps

Run this Colab - https://colab.research.google.com/drive/1dXver-IrwMz4aBnkW2GSLo9gmHEIn2Iu?usp=sharing

**Comment by dbickson** [comment]
HI @dnth I believe the [::,::,::] may slow down I think they are more efficient ways, you can do it with cv2 .
Not sure if the pil image open actually reads the image or is it a lazy operation just opening a file handle?

**Comment by dbickson** [comment]
Take a look here and feel free to extend the func to support your needs
```def inner_read(img1_path):
    if img1_path.lower().endswith('.heic') or img1_path.lower().endswith('.heif'):
        img = Image.open(img1_path)
        assert img is not None, f"Failed to open image from {img1_path}"
        img = np.array(img)
        channels = img.shape[-1] if img.ndim == 3 else 1
        if channels == 1:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        elif channels == 4:
            img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        else:
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    else:
        img = cv2.imread(img1_path, cv2.IMREAD_UNCHANGED)
    assert img is not None, f"Failed to open image from {img1_path}"
    if img.dtype == 'uint16':
        img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)
        channels = img.shape[-1] if img.ndim == 3 else 1
        if channels == 1:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        elif channels == 4:
            img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    return img
```

**Comment by dnth** [comment]
Thanks Danny. I ran a quick comparison using cv2. The cv2 run time fluctuates but always take longer than numpy `img[:, :, ::-1]`

![image](https://github.com/visual-layer/fastdup/assets/6821286/53a9dd18-d864-4d94-a336-3a620aeabab8)

**Comment by dnth** [comment]
To rule out the possibility of laze execution, I display the image and made a comparison.

+ Using fastdup_imread + numpy
![image](https://github.com/visual-layer/fastdup/assets/6821286/b9a7559f-695f-461f-b8a4-74fd0012e9e0)


+ Using fastdup_imread + cv2
![image](https://github.com/visual-layer/fastdup/assets/6821286/2e3d24e2-ec5d-45fd-ba54-3957b09dd5a4)

+ Using PIL.Image
![image](https://github.com/visual-layer/fastdup/assets/6821286/58b4cb72-92c0-4364-9a2f-f1239d76713c)
