### ISSUE TITLE
Doesn't work if images are in S3 Sub directories

### ISSUE THREAD

**Issue by sudharshankakumanu** [visual-layer/fastdup#29]
- Works only if all images are in a flat structure (all images in one directory).
- This is not a feasible layout , especially for millions of images.

**Comment by visualdatabase** [comment]
Hi @sudharshankakumanu we will look into it today. It is supposed to work. Can you please run with verbose=1, num_images=100 and send us the printed out aws s3 command and any error message you may observed. We did find that if there is no folder name just the bucket, there may be an issue (we assume bucket name plus folder name).

**Comment by visualdatabase** [comment]
<img width="1446" alt="צילום מסך 2022-11-22 ב-7 20 35" src="https://user-images.githubusercontent.com/105352401/203228488-c9c3e866-906c-4732-b185-4b0f58364885.png">
Hello @sudharshankakumanu as observed by this screenshot, collecting images from multiple s3 subfolder works for us. We will need more information to reproduce your issue.

**Comment by sudharshankakumanu** [comment]
@visualdatabase
Yes, having just a bucket name is the Issue, I have my Laion 2b data in this structure **s3://{bucket-name}/{0...n}/***.jpg**

and I get the following error:

`fastdup.run(input_dir="s3://test-kakumanu/", work_dir='fastdup-test', nearest_neighbors_k=5, turi_param='ccthreshold=0.96')
FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
Going to loop over dir s3://test-kakumanu/
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 0)
Aborted`

May be adding another level of sub-directory would solve the problem, but unfortunately in case S3 it means migrating entire data, but thanks for your response, any plans to fix this ?

**Comment by sudharshankakumanu** [comment]
I am working on Ubuntu 18.04. I'd be happy to be added to the slack community. Just sent you an e-mail. Looking forward, Thanks

**Comment by amiralush** [comment]
@sudharshankakumanu please join our slack using this link:
https://visualdatabase.slack.com/join/shared_invite/zt-19jaydbjn-lNDEDkgvSI1QwbTXSY6dlA#/shared-invite/email

**Comment by dbickson** [comment]
Should be fixed in 0.164
