### ISSUE TITLE
Stuck on running "FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson" [Bug]: 

### ISSUE THREAD

**Issue by dominicco** [visual-layer/fastdup#305]
### What happened?

Hi! When I run "fd.run(model_path='/content/dinov2_vits14.onnx', cc_threshold=0.8, d=384)" its stuck running forever. its been an hour and hasn't finished. Is this normal? How long should it take?

### What version of fastdup were you runnning on?

1.73

### What version of Python were you running on?

Python 3.10

### Operating System

Linux Colab

### Attach a screenshot [Optional]

<img width="631" alt="33333333333333" src="https://github.com/visual-layer/fastdup/assets/21361114/93d4f898-35d9-4fb8-b0c7-40fade0f249c">

**Comment by dbickson** [comment]
HI @dominicco the problem is with the jupyter terminal swallowing the output from c side fastdup. Can you please run on regular python terminal and let us know what you see.

**Comment by domini8888** [comment]
It worked!!! Thank you very much!!!!!
