### ISSUE TITLE
[Feature Request]: Allow search on multiple work dirs in parallel

### ISSUE THREAD

**Issue by Tompil3r** [visual-layer/fastdup#309]
### Feature Name

Multiple searches in parallel

### Feature Description

Currently `fastdup.init_search(k=k, work_dir=work_dir)` makes the given work_dir the active one for search, and so if search on multiple work dirs is needed in parallel (in the same process), it is required to run init_search each time - which might take a significant amount of time.

**Comment by dbickson** [comment]
done in 1.89
