### ISSUE TITLE
[Bug]: Pinned `requests` makes `fastdup` incompatible with other packages

### ISSUE THREAD

**Issue by lsorber** [visual-layer/fastdup#315]
### What happened?

Because `fastdup` depends on a pinned `requests==2.28.1`, it cannot be installed together with other packages that have different requirements on `requests`.

For example, it is impossible to install `fastdup` and [Label Studio](https://github.com/HumanSignal/label-studio) in the same virtualenv.

### What did you expect to see?

That `fastdup` only puts lower bounds on it dependencies in general. Specifically, that the pin on `requests` is relaxed.

### What version of fastdup were you runnning on?

1.89

### What version of Python were you running on?

Python 3.10

### Operating System

Debian

### Reproduction steps

`pip install fastdup label-studio`

**Comment by dnth** [comment]
This is not a solution but a temporary workaround. Perhaps try 

`pip install fastdup --no-deps -U`?

**Comment by lsorber** [comment]
Thanks for the suggestion @dnth, however, that won't work in our case as we're using Poetry.

**Comment by dbickson** [comment]
Hi @lsorber we have release version 1.90 for ubuntu 20 and mac m1 relaxing requests requirement. Please try it out and let us know if this works for you.
