### ISSUE TITLE
Use fastdup in code pipeline rather than reports

### ISSUE THREAD

**Issue by UsmanAliKhan60** [visual-layer/fastdup#320]
### Feature Name

Using in pipeline

### Feature Description

[Feature Request]: Hello, I am trying to use fastdup to check quality of webcam. I want to detect face, lightness or darkness and blurriness. Based on these features I want to check if webcam is good or not. Currently fastdup takes dataset folder as input and save the output of blurriness in the form of report in .html format. Is there any method to pass the image to fastdup to get the response in the code rather than saving in the report?

**Comment by dbickson** [comment]
HI @UsmanAliKhan60, your request is already supported.
Fastdup creates output files, for example fd.img_stats() 
https://visual-layer.readme.io/docs/v1-api#fastdup.fastdup_controller.FastdupController.img_stats
returns a dataframe with the image statistics, you can filter blurry images from the blur values computed.

For example:
```
import fastdup
fastdup.run('/my/data/", work_dir="out")
delete 5% of the brightest images and delete 2% of the darkest images
fastdup.delete_or_retag_stats_outliers("out", metric="mean", lower_percentile=0.05, dry_run=False)
```

Let us know if you need any further help.

**Comment by aliayub40995** [comment]
Thanks. I am able to get the results in code using fd.img_stats(). But the results are also getting saved in work_dir folder. I dont want to create the work_dir folder only use the results in the code. Can I do this?

**Comment by dbickson** [comment]
Hi @UsmanAliKhan60 fastdup need some scratch space to put intermediate files. You can safely delete this directory once you are done with the computation.
Best,
