### ISSUE TITLE
[Bug]: Can't pip install

### ISSUE THREAD

**Issue by abehzadnia** [visual-layer/fastdup#325]
### What happened?

Can't pip install fastdup 
```
ERROR: Could not find a version that satisfies the requirement fastdup (from versions: none)
ERROR: No matching distribution found for fastdup
```

### What version of fastdup were you runnning on?

NA

### What version of Python were you running on?

Python 3.10

### Operating System

Windows 11

**Comment by dbickson** [comment]
HI @abehzadnia, on Windows fastdup support python 3.9 only. Can you try with python 3.9?
