### ISSUE TITLE
[Feature Request]: Unpin dependencies

### ISSUE THREAD

**Issue by fairead** [visual-layer/fastdup#329]
### Feature Name

Unpin dependencies

### Feature Description

I wish to suggest for unpinning of fastdup dependencies to allow users to use their own selected dependency versions. For example, the current fastdup v2.2 still uses pandas v2.0.3 whereas the latest pandas version is currently of v2.2.2.

**Comment by dbickson** [comment]
hi @fairead it is difficult to remove pinned deps, since we support multiple operating systems including windows, linux and mac and each one has their own constraints. I suggest to install fastdup as usual, then you can upgrade pandas and it should work fine. (Try it out and let us know).

**Comment by wickeat** [comment]
@dbickson It seems like the dependencies are no longer pinned to a specific version, e.g. pandas. Can you please confirm?

**Comment by dbickson** [comment]
Hi @wickeat  I see pandas>=2.0.3
