### ISSUE TITLE
[Feature Request]: How to block the version check ? 

### ISSUE THREAD

**Issue by wangxiong172086864** [visual-layer/fastdup#335]
### Feature Name

block the version check

### Feature Description

Want some method to block the version check of fastdup,  in th python code ,  export FASTDUP_PRODUCTION='1',  but still failed when running the fastdup program.

**Comment by wangxiong172086864** [comment]
@dbickson Any suggestion about this ?

**Comment by dnth** [comment]
@wangxiong172086864 did you run fastdup in the same terminal after running `export FASTDUP_PRODUCTION='1',`?

**Comment by wangxiong172086864** [comment]
> @wangxiong172086864 did you run fastdup in the same terminal after running `export FASTDUP_PRODUCTION='1'`?

yes, before export FASTDUP_PRODUCTION='1',  the code failed at import fastdup,  after  export FASTDUP_PRODUCTION='1', the code failed at running fastdup.run()

**Comment by dbickson** [comment]
Can you please end us the full command you run and full error log? run with verbose=1 so we could debug. thanks
