### ISSUE TITLE
Проблема с установкой на windows10

### ISSUE THREAD

**Issue by BorodinAG** [visual-layer/fastdup#339]
Добрый день. Столкнулся с проблемой установки на windows 10. Никак не мог установить. Кое как установил, но не могу запустить. Ваша программа работает локально? С Idea работает? Я не могу её установить в ItellyIdea, постоянно ошибка установки. Пробовал сделать работу VisualCode, та же проблема. Как это решить?

**Comment by dbickson** [comment]
Hi @BorodinAG. We suggest to install WSL2 on windows and then open a terminal and install as if you are in ubuntu. Let us know if this works.

**Comment by BorodinAG** [comment]
Добрый день. Я до этого всё это сделал. Она как бы устанавливается, но локально не работает. Если её устанавливать на Colab, то всё работает. Но  я хочу установить локально и работать локально. Работать из IntellyIdea, а там вообще говорит: ошибка установки.
PS C:\Users\Алексей\ideaprojects\parser\venv\scripts> pip install fastdup
ERROR: Could not find a version that satisfies the requirement fastdup (from versions: none)
ERROR: No matching distribution found for fastdup
 
В VSCode тоже самое. 
>Воскресенье, 7 июля 2024, 15:10 +03:00 от Danny Bickson ***@***.***>:
> 
> 
>Hi  @BorodinAG . We suggest to install WSL2 on windows and then open a terminal and install as if you are in ubuntu. Let us know if this works.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <visual-layer/fastdup/issues/339/2212428534 @ github . com>
 
 
--
С уважением, Алексей Бородин.

**Comment by Tompil3r** [comment]
@BorodinAG if you installed WSL please make sure to enable it by running `wsl.exe` in cmd or powershell, afterwards make sure you have a python version that fastdup supports (python3.9/python3.10/python3.11), then update pip using the following:
`python3.x -m pip install pip -U`
and then install fastdup using `python3.x -m pip install fastdup.`

**Comment by BorodinAG** [comment]
Добрый день. Оно не ставится и не работает. Если пробуешь установить python3.1, выдает ошибку — такого нет. Тогда как её установить и работать?

  
>Воскресенье, 7 июля 2024, 16:14 +03:00 от Tompil3r ***@***.***>:
> 
> 
>@BorodinAG if you installed WSL please make sure to enable it by running wsl.exe in cmd or powershell, afterwards make sure you have a python version that fastdup supports (python3.9/python3.10/python3.11), then update pip using the following:
>python3.x -m pip install pip -U
>and then install fastdup using python3.x -m pip install fastdup.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <visual-layer/fastdup/issues/339/2212446931 @ github . com> 
 
 
--
С уважением, Алексей Бородин.

**Comment by BorodinAG** [comment]
Добрый день. Если не трудно, напишите, пожалуйста, полный цикл установки вашего по на windows 10. По текущему пробовал ничего не получается. С python 3.10.19, 3.11.9 не работает. С ubuntu последней 22.04 не работает. Даже систему сносил, но не помогло. Напишите, пожалуйста, последовательно все команды и версии программ, с которыми точно всё заработает. Вчера оставил голую систему. Хочу добиться нормальной работы программы. Жду ответа.
--
Отправлено из Mail.ru для Android воскресенье, 07 июля 2024г., 16:14 +03:00 от Tompil3r  ***@***.*** :

**Comment by dbickson** [comment]
Hi @BorodinAG can we set up a short zoom call tomorrow to go over your issue so we could guide you in the installation process? Do you speak English or just Russian?

**Comment by dbickson** [comment]
Hi @BorodinAG let me know if you still have an issue, we will be happy to help.
