### ISSUE TITLE
[Bug]: Fastdup only accepts one object per image in COCO format

### ISSUE THREAD

**Issue by kasperschnack** [visual-layer/fastdup#350]
### What happened?

When using fastdup with a COCO format dataset, it only recognizes and processes one object per image, first one in the list of annotations, even when multiple objects are present in the annotations.

### What did you expect to see?

I expected fastdup to process and recognize all annotated objects per image in the COCO format dataset, allowing for handling images with multiple images.

### What version of fastdup were you runnning on?

2.13

### What version of Python were you running on?

Python 3.9

### Operating System

Mac OS Sonoma 14.7.1 (23H222)

### Reproduction steps

1. Prepare a COCO format dataset with multiple objects annotated per image

put all images and annotations.json in imgs/ folder

2. Run fastdup on the prepared dataset using jupyter notebook

```
import fastdup

fd = fastdup.create(input_dir="imgs/")
fd.run()

fd.explore()
```

3. Observe the output and visualizations

Notice that only one object per image is recognized and processed

### Relevant log output

No errors are shown

### Attach a screenshot [Optional]

![image](https://github.com/user-attachments/assets/b5a323f4-16a2-4c76-aec8-c19497b342d9)

Only category 133 is shown for image 706. If i switch around the order of the categories such that 54 is first - that is the one that will be registered

### Contact Details [Optional]

okps@novonordisk.com

**Comment by Tompil3r** [comment]
Hi @kasperschnack,
fastdup removes bounding boxes with the exact same coordinates in the same image. Hope this clears things up.

**Comment by kasperschnack** [comment]
Hi @Tompil3r

Thank you very much for that clarification! Indeed that solves the mystery!

**Comment by kasperschnack** [comment]
Maybe it would be a good idea to print a warning when this happens? Other people might be confused by this as well

**Comment by dbickson** [comment]
This is a great idea. We will add this warning and report once completed soon.
