### ISSUE TITLE
[Feature Request]: Compatibility with COCO json files including multiple bounding boxes and segmentations

### ISSUE THREAD

**Issue by MatthiasDR96** [visual-layer/fastdup#354]
### Feature Name

Real COCO Compatibility

### Feature Description

In the 'examples/analyzing-object-detection-dataset.ipynb' there is claimed that FastDUP can read COCO json files and convert them to the FastDUP format: "fastdup requires the annotations to be in a specific format. We will use a simple converter to convert the COCO format JSON annotation file into the fastdup annotation dataframe. This converter is applicable to any dataset that uses the COCO format." However, the file they load is not json but CSV and the format specified cannot handle multiple bounding boxes and segmentations. A feature that provides compatibility with a real COCO json file would be valuable. 

### Contact Information [Optional]

matthias@superlinear.eu

**Comment by dnth** [comment]
Hi @MatthiasDR96 you can pass in the coco json into `fd.run`

for example

```python
fd = fastdup.create(input_dir='./DASH-DIET-101-4/train')
fd.run(annotations='DASH-DIET-101-4/train/_annotations.coco.json')
```

Have a look at this notebook - https://github.com/visual-layer/fastdup/blob/main/examples/analyzing-roboflow-datasets.ipynb

Does this work for you?

Each row on the dataframe represents one bounding box annotation. If there are multiple boxes for each image, you will see multiple rows on the dataframe with difference bounding box coordinates but with the same filename.

**Comment by MatthiasDR96** [comment]
Hi! 

Thanks for your answer.

It seems that the COCO is correctly loaded in the DataFrame indeed. However, when i run fd.explore(), I see no annotations in the webserver gallery. The gallery exist of separate folders of images with 'No labels available'. Also no objects are available. So can I also analyze annotations in the visualizer?

Kind regards

**Comment by amiralush** [comment]
@MatthiasDR96 please try and use Visual-Layer solution on cloud at app.visual-layer.com

In case you would like to have a demo, please email me directly at: amir@visual-layer.com
