### ISSUE TITLE
[Bug]:  Higher versions of fastdup cannot handle situations within 10 images.

### ISSUE THREAD

**Issue by zczczc11122** [visual-layer/fastdup#355]
### What happened?

```
import os 
os.environ['FASTDUP_PRODUCTION'] = '1' 
import fastdup 
fd = fastdup.create(work_dir='work_dir', input_dir='img_cache_folder') 
fd.run(ccthreshold=0.97, d=960, overwrite=True, run_mode=1, high_accuracy=True)
```
There are only 5 pictures in the `img_cache_folder` path

I have encountered an error when encountering a lower version of fastdup before, even adding the environment variable 'FASTDUP_PRODUCTION' cannot solve the problem.
```
Running the above code reports an error
[FATAL] This fastdup version is deprecated, please reinstall from pypi using pip install fastdup
```

So we upgraded the fastdup version to 2.13, but we encountered new problems with the higher version of fastdup. But when we run the above code to process data within 10 pictures, an error will be reported.
`CRITICAL:vl.root.fastdup.pipeline.common.dataset_db_updater:"Error: Insufficient number of valid images in dataset (2). Minimum required images: 10". Please note that only the following image formats are supported: ['.png', '.jpg', '.jpeg', '.gif', '.giff', '.tif', '.tiff', '.heic', '.heif', '.bmp', '.webp', '.jfif', '.jpg2'], info: None, exception: None`

Since we are an automated process, there may be situations where there are less than 10 pictures, and this will not cause an error in lower versions (such as version 2.2). Now I want to handle the situation where there are less than 10 pictures. How should I solve it? , because I did not see the documentation related to the 2.XX version here https://visual-layer.readme.io/docs/v02xx-api

### What did you expect to see?

Can handle situations within 10 pictures

### What version of fastdup were you runnning on?

2.13

### What version of Python were you running on?

Python 3.9

### Operating System

ubuntu 22.04 LTS

**Comment by dbickson** [comment]
Hi @zczczc11122 please try to define an environment variable 
```
export MIN_NUM_OF_IMAGES=2
```
Let us know if this works.

**Comment by zczczc11122** [comment]
> 你好@zczczc11122请尝试定义一个环境变量
> 
> ```
> export MIN_NUM_OF_IMAGES=2
> ```
> 
> 如果有效请告知我们。

We tried the solution you provided and this solved our problem, thanks for your reply
