### ISSUE TITLE
v0.165 is no longer compatible with python:3.8-buster docker image

### ISSUE THREAD

**Issue by jhendriksen-jh** [visual-layer/fastdup#40]
We have been running `fastdup` inside of a `python:3.8-buster` docker image for several months now. As of this morning with the latest v0.165 release we have started to see a library error when trying to import `fastdup` that we weren't seeing previously. We've now pinned to v0.163 to resolve this but still wanted to bring it to your attention.

Error seen: 
```import fastdup
venv/lib/python3.8/site-packages/fastdup/__init__.py:70: in <module>
    dll = CDLL(so_file)
/usr/local/lib/python3.8/ctypes/__init__.py:373: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: libunity_shared.so: cannot open shared object file: No such file or directory

**Comment by dbickson** [comment]
Hello @jhendriksen-jh great to hear that you are using fastdup for a few months! We would love to work with you to debug and solve this issue.
We have just uploaded our docker image: docker.io/karpadoni/fastdup-ubuntu-20.04 and verified that fastdup v 0.165 works there. See the below screenshot:
![Screen Shot 2022-11-23 at 17 23 15](https://user-images.githubusercontent.com/4495523/203583865-c5eb5a65-1486-480d-97db-439687ec527d.png)
Can you use our own docker or do you have anything special on your docker? 

Can you please ls and send us the contents of your library `ls venv/lib/python3.8/site-packages/fastdup/` and the output of `find venv/lib/python3.8/site-packages/fastdup/lib`. Also can you try to do `export LD_LIBRARY_PATH=venv/lib/python3.8/site-packages/fastdup/lib` inside the docker. (Better use full path I am not sure what is the full path inside the docker). And then run python3.8 and let us know if this works.

**Comment by dbickson** [comment]
hi @jhendriksen-jh let us know once you have more information we would like to understand the source of this problem.

**Comment by jhendriksen-jh** [comment]
Sorry for taking a bit to respond - I was out of office for the holiday. To me it looks like an Ubuntu 18.04 compatibility issue. I created a new virtual environment on my workstation and installed `fastdup v0.165` and recreated the error message I received above by trying to import it in a python terminal. 

Here's the full traceback with hopefully some more helpful context: 
```>>> import fastdup
Traceback (most recent call last):
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/fastdup/__init__.py", line 73, in <module>
    dll = CDLL(so_file)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libunity_shared.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/fastdup/__init__.py", line 73, in <module>
    dll = CDLL(so_file)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libunity_shared.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/fastdup/__init__.py", line 75, in <module>
    fastdup_capture_exception("__init__", ex)
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/fastdup/sentry.py", line 42, in fastdup_capture_exception
    capture_exception(section, e)
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/sentry_sdk/api.py", line 97, in capture_exception
    return Hub.current.capture_exception(error, scope=scope, **scope_args)
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/sentry_sdk/hub.py", line 380, in capture_exception
    exc_info = exc_info_from_error(error)
  File "/home/cidza3z/fastdup/lib/python3.8/site-packages/sentry_sdk/utils.py", line 798, in exc_info_from_error
    raise ValueError("Expected Exception object to report, got %s!" % type(error))
ValueError: Expected Exception object to report, got <class 'str'>!
```

Output of ls: 
```ls fastdup/lib/python3.8/site-packages/fastdup
coco.py              libfastdup_shared.so
confusion_matrix.py  __pycache__
cvat.py              sentry.py
definitions.py       tensorboard_projector.py
galleries.py         UndisclosedFastdupModel2.ort
html_writer.py       UndisclosedFastdupModel2.required_operators.config
image.py             UndisclosedFastdupModel.ort
__init__.py          UndisclosedFastdupModel.required_operators.config
label_img.py         utilts.py
lib                  webdataset.py
```

Output of find: 
```find fastdup/lib/python3.8/site-packages/fastdup/lib
fastdup/lib/python3.8/site-packages/fastdup/lib
fastdup/lib/python3.8/site-packages/fastdup/lib/libGL.so.1
fastdup/lib/python3.8/site-packages/fastdup/lib/libcurl.so
```

The same exception occurs after exporting the LD_LIBRARY_PATH to set it to what was suggested (inside the specific venv I was testing with)

**Comment by dbickson** [comment]
HI @jhendriksen-jh thanks for the detailed feedback, we found the source of the issue, something changed with auditwheel --repair packaging we are using, somehow it did not detect correctly some of the needed packages and they where removed from the whl. We are working on a fix to share soon.

**Comment by dbickson** [comment]
HI @jhendriksen-jh please try v 0.170 and let us know if this works? If not try to export LD_LIBRARY_PATH to the fastup/lib subfolder.

**Comment by jhendriksen-jh** [comment]
v0.170 looks good to go. It performed as expected in all of our use cases. Thanks for looking into this so quickly!
