### ISSUE TITLE
fastdup fails to read very small images

### ISSUE THREAD

**Issue by Tompil3r** [visual-layer/fastdup#41]
Happens when image dimensions are ~8px and smaller

<img width="959" alt="image" src="https://user-images.githubusercontent.com/67478051/205934634-5e00e4b0-b309-401c-aeb6-29e4cb896936.png">

**Comment by dbickson** [comment]
Issue was because we do not allow images smaller than 10x10, we have clarified the error message on version 0.173 to be released today.
