### ISSUE TITLE
Requests and packaging dependecies are missing as requirements

### ISSUE THREAD

**Issue by dimafrid** [visual-layer/fastdup#47]
After installing fastdup with 

> python3 -m pip install fastdup

,

> import fastdup

fails on

> ModuleNotFoundError: No module named 'packaging'
ModuleNotFoundError: No module named 'requests'

pip-installing those missing requirements solves the issue.

**Comment by dimafrid** [comment]
> ~ % python3 -m pip -V
pip 22.3.1 from /Users/dimafrid/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)

[pip-verbose.txt](https://github.com/visual-layer/fastdup/files/10251303/pip-verbose.txt)

> python3
Python 3.8.9 (default, Apr 13 2022, 08:48:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> ~ % sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62

thanks @dbickson for looking into this, hope it's not a false alarm.

**Comment by dbickson** [comment]
Hi @dimafrid about requests you are right, packaging I have no clue which dep is requiring it. I will add requests to begin with on the next release.

**Comment by dbickson** [comment]
Should be fixed in 0.180 it was our bug
