### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)

### ISSUE THREAD

**Issue by amiralush** [visual-layer/fastdup#54]
Running on GCP, ubuntu 20 and getting the following warning after running "import fastdup":

_/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "_

**Comment by dbickson** [comment]
For my ubuntu 20 I don't see this, which python version and which requests (pip3 freeze | grep requests)

**Comment by dbickson** [comment]
Should be fixed in 0.182, problem was not latest requests package
