### ISSUE TITLE
sh: 1: ffmpeg: not found

### ISSUE THREAD

**Issue by amiralush** [visual-layer/fastdup#55]
When trying to run on a folder of videos I am getting the following error.

I have installed ffmpeg on Ubuntu 20 with: sudo apt-get install ffmpeg

**Comment by dbickson** [comment]
Need to make sure ffmpeg is found on the path, namely you can open a terminal and un ffmpeg and the command is found. If it is not found do a symbolic link between where you installed ffmpeg to to /usr/bin (sudo ln -s <path to ffmpeg> /usr/bin)

**Comment by dbickson** [comment]
Fixed error message should be fixed in 0.192
