### ISSUE TITLE
matplotlib is a requirement for running create_stats_gallery, but is not installed as part of fastdup dependencies

### ISSUE THREAD

**Issue by dimafrid** [visual-layer/fastdup#57]
> fastdup.create_stats_gallery(os.path.join(results_dir, 'atrain_stats.csv'), save_path=results_dir, metric='size')
fails on missing matplotlib. Is it by design?

fastdup version: 0.190
(Info about fastdup installation method, python, pip and machine versions can be found in https://github.com/visual-layer/fastdup/issues/47)

Thanks!

P.S. BTW, Dockerfile lists matplotlib explicitly.

**Comment by dbickson** [comment]
Fixed error message to be clearer on 0.192
