### ISSUE TITLE
[fastdup.create_duplicates_gallery] Is the following an expected behavior of descending argument?

### ISSUE THREAD

**Issue by dimafrid** [visual-layer/fastdup#58]
The following is the result of running
`fastdup.create_duplicates_gallery(os.path.join(results_dir, 'similarity.csv'), results_dir, num_images=200)`

<img width="1512" alt="Screen Shot 2023-01-01 at 18 57 42" src="https://user-images.githubusercontent.com/48483/210178861-a9fc8190-ba3e-4e96-97a0-d37ae99f69a3.png">

When running
`fastdup.create_duplicates_gallery(os.path.join(results_dir, 'similarity.csv'), results_dir, num_images=200, descending=False)`
, the result looks like the following:

<img width="1512" alt="Screen Shot 2023-01-01 at 19 01 35" src="https://user-images.githubusercontent.com/48483/210178936-e997e4ea-82e0-43a5-aabc-15bf67e85887.png">

Notice that the distance is still descending, but it doesn't start with 1.0 anymore.

fastdup version: 0.190

Thanks!

**Comment by dbickson** [comment]
Was able to reproduce the issue, will be fixed in 0.196
