### ISSUE TITLE
[fastdup.create_similarity_gallery] Is descending argument supported?

### ISSUE THREAD

**Issue by dimafrid** [visual-layer/fastdup#59]
Seems like running 
`fastdup.create_similarity_gallery(os.path.join(results_dir, 'similarity.csv'), results_dir,
                                  num_images=100, descending=False)`
and
`fastdup.create_similarity_gallery(os.path.join(results_dir, 'similarity.csv'), results_dir,
                                  num_images=100, descending=True)`
yield the same result, which is basically unordered:

<img width="1512" alt="Screen Shot 2023-01-01 at 19 19 56" src="https://user-images.githubusercontent.com/48483/210179405-1b931800-0223-4969-b4b6-3d01bfeb3b2b.png">

fastdup version: 0.190

Thanks!

**Comment by dnth** [comment]
@dimafrid I'm using version 0.189 and it seems to work for me.

**Comment by dbickson** [comment]
Fixed in 0.195
