### ISSUE TITLE
delete_or_retag_stast_outliers incorrect parameters when using how='move'

### ISSUE THREAD

**Issue by PedroPachuca** [visual-layer/fastdup#63]
the function delete_or_retag_stast_outliers does not pass save_path to inner_delete when how=='move' thereby causing the assert statement in inner_delete to fail every time

**Comment by PedroPachuca** [comment]
I upgraded to v0.196 but unfortunately got the same error. From the stacktrace, I see that the inner_delete function call still doesn't pass the save_path argument when how=='move'.

I don't believe the github repo is updated to v0.196 so I cannot verify but I suspect that the change was not pushed properly.

**Comment by PedroPachuca** [comment]
super easy fix, fixed it locally. Can pull request if you like, but it's probably easier to just make the change and push yourself.
![Screenshot from 2023-01-09 11-16-16](https://user-images.githubusercontent.com/14255680/211389574-9b208cb0-e6d9-4589-8183-a2c6b43746d6.png)

**Comment by dbickson** [comment]
Hi @PedroPachuca this is very strange so I did fix it on my side. Are you sure you installed using -U --force-reinstall flags? Maybe the version was not updated? On my side I see the following code: 
<img width="683" alt="Screen Shot 2023-01-09 at 21 49 04" src="https://user-images.githubusercontent.com/4495523/211395174-ce477441-8270-4438-b63e-0672055287f4.png">
Anyway apologies that will be fixed again next version we will double check again.

**Comment by PedroPachuca** [comment]
when I pip show, I see the right version of v0.196. Not sure why the right version is not being downloaded properly. In any case, I'm sure it will propagate with a future release, and I've fixed it locally for my use case. Great tool!
