### ISSUE TITLE
'ration' in output plot titles, should the word be 'ratio'?

### ISSUE THREAD

**Issue by apiszcz** [visual-layer/fastdup#66]
The axis label is 'ratio' however the plot title is ration?

![image](https://user-images.githubusercontent.com/1430861/213921726-d89a354c-4c95-4990-8d70-c0e25ba2049a.png)

**Comment by dbickson** [comment]
hi @apiszcz thanks for reporting, we will fix the typo in v. 0.203 coming out soon. Feel free to reach out for any other issues!
