### ISSUE TITLE
Running with pre-computed embeddings

### ISSUE THREAD

**Issue by yzou2** [visual-layer/fastdup#68]
Hi, 

Thanks for open sourcing the great package. Is there a feature to use my own pre-computed embeddings for setup/clustering etc, rather than inference for embeddings on the fly?

**Comment by dbickson** [comment]
Hi @yzou2, yes of course as described here:
https://github.com/visual-layer/fastdup/blob/main/RUN.md#external
Let us know if you need any additional help.

**Comment by dbickson** [comment]
Closing, please reopen if you see any issue
