### ISSUE TITLE
Can't run similarity search when validation file is smaller than training data.

### ISSUE THREAD

**Issue by bigmb** [visual-layer/fastdup#70]
I am currently trying to run validation test on different types of datasets. But it's throws an error when the size of the validation dataset is less than the size of the trained dataset.

For example: 
My training dataset: 100K events
My validation dataset: 173K events. 
Error: 
`2023-02-06 17:42:52 [INFO] 1151) Finished load_index() NN model, num_images 100000`
`2023-02-06 17:42:52 [INFO] Read nnf index file from sliced_test2/dataset_100000/nnf.index 1`
`Failed assertion num_images_test*max_augmentations <= from 174381.0000 105171.0000` `/home/ubuntu/visual_database/cxx/src/nnf.h:436
`

**Comment by dbickson** [comment]
Hi @bigmb thanks for reporting, indeed an interesting corner case ! We assumed training data had to be bigger than test data. We found the issue and will submit a fix in v. 206 very soon.

**Comment by dbickson** [comment]
v. 0.206 released for ubuntu 20 please check
