### ISSUE TITLE
Exception in do_create_outliers_gallery

### ISSUE THREAD

**Issue by IdoBl** [visual-layer/fastdup#72]
Version: 0.204
When running create_outliers_gallery with how="all"
line 485: dups_file = os.path.join(os.path.dirname(outliers_file), FILENAME_SIMILARITY)
TypeError: expected str, bytes or os.PathLike object, not DataFrame

outliers_file converted to DataFrame before being sent to method but method try to use it as a string path.

**Comment by dbickson** [comment]
Thanks @IdoBl for the bug report. We have submitted a fix should be released today in 0.207 please try it out
