### ISSUE TITLE
GCP cloud storage support

### ISSUE THREAD

**Issue by GeorgePearse** [visual-layer/fastdup#83]
This is an excellent tool, and I've already got some real value out of it. 

The majority of our image data sits on GCP and we're trying to reduce our storage costs without wasting data that could be used for training, would there be a way to run it over that without loading to disk (aware of the S3 support)?

**Comment by dbickson** [comment]
Hi @GeorgePearse thanks for your kind words! 

To clarify your question you are asking if you can do analytics on files stored in google storage without copying it first to a google compute node and then paying for network traffic and compute? Unfortunately I am afraid this is not possible. 

We do support cases where the data size is larger than the local disk you can create the feature vectors and delete the images after they are seen once. 

Please clarify some more and we will try to help!

**Comment by GeorgePearse** [comment]
```
We do support cases where the data size is larger than the local disk you can create the feature vectors and delete the images after they are seen once.
```

Think this is what I'm after. So I could do things like create the components, and then pull down a few examples as required to see what a component represents?

**Comment by dbickson** [comment]
Hello @GeorgePearse you have an interesting use case, can we setup a short zoom call to discuss how can we help ?

**Comment by dbickson** [comment]
Hi @GeorgePearse please reopen if this is still relevant
