### ISSUE TITLE
Understanding the algorithm

### ISSUE THREAD

**Issue by abulus** [visual-layer/fastdup#92]
Hello, First of all thanks for sharing this repo.

I'd like to ask how do we extract features from images. I checked the documentations but couldn't find the exact answer to clear my doubts. There are `run_mode` parameter to extract features from images but I wonder how do we extract. Are we following traditional methods or models? 

Hope this question does not violate your terms of licence so I and others can get an idea.

**Comment by dbickson** [comment]
HI @abulus we use our own unsupervised deep learning trained model, which is trained on natural images and scores an image in 2 msec. It is also possible to give `model_path` and point to any onnx/ort model of your choosing to extract features using other models. Let us know if this is helpful.

**Comment by dbickson** [comment]
HI @abulus once you are free please submit the required information and we will help you solve your issue.
Many thanks!
